layout: default
title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
github_username:  MirakelPrints
github: [metadata]

url: https://MirakelPrints.github.io

remote_theme: pmarsceill/just-the-docs
color_scheme: dark

plugins:
  - jekyll-feed
  - jemoji

callouts_level: loud
callouts:
  prereqs:
    title: Prerequisites
    color: yellow
  compat:
    title: Compatibility
    color: pink
  warning:
    title: Warning
    color: red
  attention:
    color: orange
  note:
    title: Note
    color: blue

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Issues, Feedback, & Contributions":
    - "https://github.com/MirakelPrints/MirakelPrints.github.io/issues"
